### PR TITLE
new: read INDI and FAM from clippings cart

### PR DESCRIPTION
**Pull request by hartenthaler**
This is the first draft!

If the clippings cart is empty then everything should be as before. If there is content in the clippings cart that is used instead of the function addIndiToList(). This should be in the final version a button in the first part of the menu, but for testing this should be ok. Or following my original idea: remove the first part (selecting individuals and families) completely, but then GVExport depends on the clippings cart.

What has to be done:
- add personal photos to the individuals
- support for "combined" mode 

Some initial tests have shown, that GVExport is working perfectly for data sets defined by other functions. About 1300 individuals and 60 families can be shown, but 1300 individuals and 800 families result in a memory problem.

### CODE REVIEW

**Comment by hartenthaler** [comment]
Edit: now I was able to show 1300 persons in 800 families (deselecting "add URL" and not showing XREFs).

**Comment by hartenthaler** [comment]
Have you seen this pull request? Should I address it to another branch instead of the "master" branch?

**Comment by Neriderc** [comment]
I have seen it but need to wait until I'm back to my dev machine before I can test it out.

If all existing functionality still works and new functionality works ok then I think master branch should be fine. If it's not quite production-ready then it doesn't have to be merged now, I can test it out and you can keep adding commits to the pull request if you have further changes to make.

**Comment by Neriderc** [comment]
Looking good! I've tested adding things to the clippings cart and having them show, and it seems to work well (except photos and combined mode, which you've mentioned). I think when there are items in the clippings cart, we should disable/grey out the options that do not work with the clippings cart, and have a little message to explain that there are items in the clipping cart so those will be used instead of the options in the person selecting selection.

**Comment by hartenthaler** [comment]
Perfect!

So I will work on
- combined mode and
- adding photos (if they are in the clippings cart).
This will need some time because I'm on vacation for one week.

**Comment by Neriderc** [comment]
Great! Over the next month or two I'll also have less time for working on things. I'm thinking I might tackle some of the more minor bugs and changes that don't need much time to resolve, and leave the more major changes to later.

**Comment by hartenthaler** [comment]
This pull request is now outdated. I have moved all the new functions to a new file with a new class. But there are some modifications necessary in functions_dot.php

**Pull request closed without merging**
