### PR TITLE
Translate Spanish

### PR DESCRIPTION
**Pull request by yako1984**
Translate Spanish

### CODE REVIEW

**Comment by Neriderc** [comment]
Thanks for this, but from my testing this doesn't seem to work. Some phrases are translated and some aren't, possibly because of small differences meaning they aren't matched properly.

We actually have a collaborative translation project here: https://poeditor.com/join/project/YqPRBXZnlf

If you make an account and join the project, you should be able to add Spanish as a language then all the terms are listed for you to translate. I can then generate the .po file from that data.

**Comment by Neriderc** [comment]
Thanks for doing the translations! I worked out the problem, the file needs to be called "es.mo" not "es_ES.mo" to match the language code webtrees puts through when you choose Spanish as the language.

Changing the name of the file made the translations work for me :)

**Comment by yako1984** [comment]
All the translations are done, but it does not take the ones from the
dropdowns.

**Comment by Neriderc** [comment]
I'll have to take a look, sorry ran out of time so will check another time.

**Comment by yako1984** [comment]
No problem bro. It will be fixed, it is 99%. it is no problem. a greeting

**Comment by Neriderc** [comment]
This should be resolved in master now, fixed by #72

**Comment by yako1984** [comment]
La traduccion esta hecha en la web que me enviaste. Igual cuando lo vea en
la web en contexto hay que corregir alguna cosa.
un saludo

**Comment by Neriderc** [comment]
> La traduccion esta hecha en la web que me enviaste. Igual cuando lo vea en la web en contexto hay que corregir alguna cosa. un saludo

Sorry I don't speak Spanish, but my understanding is you're saying the translation is complete? When I look at the project on poeditor.com, it shows that Spanish is 49% translated.

Have you only just replied to the github email now, or did you reply at the time and for some reason github hasn't added your reply until now?

**Pull request closed without merging**
