### PR TITLE
Highlight individual changes

### LINKED ISSUE #497: Update option to highlight individuals
As per discussion in #488, we should make the following changes:
- Add help icon to context menu
- Remove option to highlight starting individuals
- Add colour selection for each individual on the list of selected individuals to show in a different colour
- Add logic when loading settings to move highlighted starting individuals into the selected starting individuals list and set the colour based on the highlighted starting individuals colour, unless the individual is already in the selected individuals list.

### PR DESCRIPTION
**Pull request by Neriderc**
Changes to highlighting individuals process:
- Remove option to highlight starting individuals
- Add colour selection for each individual on the list of selected individuals to show in a different colour
- Add logic when loading settings to move highlighted starting individuals into the selected starting individuals list and set the colour based on the highlighted starting individuals colour, unless the individual is already in the selected individuals list.
- Added person select and bells and whistles version of individuals list

Also added a help icon to the context menu when an individual is clicked, and a new help page that shows when this is clicked.

Closes #497

### CODE REVIEW

**Comment by schuco** [comment]
for long names there is an empty line addes, which requires more space than necessary:
grafik
I don't know if this came with the the latest main verion.

Otherwise the new option to mark persons with individual colours is perfect.

**Comment by Neriderc** [comment]
Looks like it's been like that for a while, but some recent changes have made it worse due to extra spacing. I will look to make an adjustment here soon, cutting off long names (I've already built this for the highlighted names, since the space was smaller due to being indented). If people need to see the full details to decide who is whom, they can click on the listed person and the diagram will scroll to that person.

**Comment by Neriderc** [comment]
This is now in the main branch.

**Comment by Neriderc** [comment]
Ah, the problem was that through another change I increased the line height, so the browser treated the line as taller than it actually is. This was fine on one line because the box is that big anyway, especially with pictures enabled, but I hadn't seen a wrapping name to see how it broke.

If you'd prefer the line break, I can change it, just let me know 🙂

**Comment by schuco** [comment]
Indeed I would prefere the line break.

**Comment by Neriderc** [comment]
Sure thing, I've updated it and will do the pull request soon to add it into the master branch.

The list of highlighted individuals won't wrap, that will still be cut off as it doesn't look great due to the much smaller space available. This was the original reason for changing it, but I have now applied it only to this list and not to the others.

**Pull request merged**
