### PR TITLE
move CSS to file and fix bug

### PR DESCRIPTION
**Pull request by hartenthaler**
I have moved the CSS from page.phtml to a CSS file. Decide if you like this, please.

As mentioned in #60 :

The following lines have to be removed from page.phtml:

        $cart = Session::get('cart', []);
        $xrefs = array_keys($cart[$tree->name()] ?? []);
        $cartempty = sizeof($xrefs) == 0;
because it is not about if the clippings cart is empty, it is about if there are no INDI records in it. This was my fault. For GVExport it is important if there is at least one person in the clippings cart, this person can be shown by GVExport. If there are only other record types in the clippings cart, then GVExport cannot show anything, so the "People to be included" standard part should be active.

The variable $cartempty in page.phtml (can be renamed to noIndiInCart, maybe) is now set in module.php in line #192.

### CODE REVIEW

**Comment by Neriderc** [comment]
I'm happy to be moving the CSS to it's own file, and at some point I'd like to do the same for the javascript functions.

What I'm concerned about is the bug #62. My biggest concern is that while it's currently fixed, I could never reproduce it. This means I have no way of testing if this change would re-introduce it.

I think I need to have a bit of a think of how I can test that this bug won't be re-introduced before I'd be happy merging in this change. While I realise this means we're keeping a bug where if you have no individuals in the cart but do have items in the cart then it causes a bug, I think this is better than having a bug that prevents the module being used _at all_.

While I don't have a lot of time for development at the moment, I'll keep thinking about how I might be able to test this.

**Comment by hartenthaler** [comment]
Yes, it is the best way to do it. the remaining bug (there is something in the clippings cart, but no INDI) is not important and we can live with that. I don't understand the reason behind bug #62. The variable $cartempty is set in module.php and transferred to page.phtml. So it is always defined. Maybe yako1984 mixed up different versions of the files. For me, that is the only reasonable explanation.

**Comment by Neriderc** [comment]
I feel it's pretty hard to mess up installation. I noticed they are using PHP-FPM, and I'm worried that might be related. My dev environment is using stock PHP, and I'm worried that differences between the versions may be causing the issue. Unless it's not possible, I think we should endeavour to support it if there's no good reason not to, so I'd like to set up a dev environment to test using PHP-FPM but there's a bit of effort in that, and I don't have time right now, though I will work on putting that together.

In the short term, it might be easier to just ask them to test it. @yako1984, are you familiar with checking out a pull request to test it? It would be great if you could confirm this change doesn't break your installation, as it re-introduces some of the changes that may have caused the bug in #62.

**Comment by Neriderc** [comment]
@hartenthaler your readme changes have been pulled through to this pull request. If you want them to be different you'll need to be careful with branches. Though it's probably easier to just keep them the same. Github will show the repository it's been forked from and which repository is ahead or behind of the other so I don't think there's too much confusion.

**Comment by hartenthaler** [comment]
grrr ... about the READme. That shouldn't be pulled through. I changed it because TheDutchJewel installed a developer version from my repository and found an intermediate error there. That was the reason to make it clear.

grrr ... about the comment. I first thought to delete this comment because the code situation at that point is now a bit easier than before, then decided to leave it as it is. But not at the correct position. Sorry.

**Comment by yako1984** [comment]
> I feel it's pretty hard to mess up installation. I noticed they are using PHP-FPM, and I'm worried that might be related. My dev environment is using stock PHP, and I'm worried that differences between the versions may be causing the issue. Unless it's not possible, I think we should endeavour to support it if there's no good reason not to, so I'd like to set up a dev environment to test using PHP-FPM but there's a bit of effort in that, and I don't have time right now, though I will work on putting that together.
> 
> In the short term, it might be easier to just ask them to test it. @yako1984, are you fa


It works perfectly and with the css corrected and well ordered. In the previous version it went wrong now it works perfectly.


Screenshot_1
miliar with checking out a pull request to test it? It would be great if you could confirm this change doesn't break your installation, as it re-introduces some of the changes that may have caused the bug in #62.

**Comment by Neriderc** [comment]
This pull request is a long way out of date from master and still has the issue with the readme. I can't edit the code and want to get this resolved so I have moved the changes as I understand them into #102 and so will close this.

**Pull request closed without merging**
