### PR TITLE
Update related checking to improve accuracy

### LINKED ISSUE #109: Check blood relative status of adopted children and partners outside displayed tree
Currently, adopted children and partners are shown as non-blood relatives (if option selected to show this in a different colour), unless a relative link is found in the displayed tree, in which case they are shown as related.

It is possible that an adopted child has been adopted from elsewhere in the family. E.g. a child being adopted by their biological uncle. Or that a partner is related, possibly distantly.

In this case, currently the record is only shown as related if this link is displayed in the diagram (i.e. uncle's parents and siblings). If this link is not displayed, then the adopted child or partner will be shown as non-related as scanning the records in the tree did not find a link.

If there is a link in the tree, then the child or partner should still be displayed as related even if the link is not shown in the diagram.

To do this, we should build an array of related records by scanning the tree starting from the initial individuals and ignoring any limits. Then compare this full list of relatives against the individuals in our diagram.

If practical, we should only do this scanning in the case it is required - i.e. a non-related adopted child is found in the tree or the "spouses" option is enabled.

See #36 for more discussion on this.

### PR DESCRIPTION
**Pull request by Neriderc**
Currently, when the related option is set, this only checks the displayed records. Where the link is not in the displayed records, the related status is shown as not related. This update will scan the full tree for relatives of starting persons, in order to determine whether an individual is related to the starting person.

Resolves #109 and may resolve several other issues.

### CODE REVIEW

**Comment by Neriderc** [comment]
@hartenthaler are you able to test this to see if it performs as you envisaged?

I have basically stopped the addIndiToList function from updating the individuals/families lists directly, and now pass in the arrays (by reference). By making this change, I can then pass in a second set of arrays with an argument to scan the full tree. I pass this back to the main scan and use it to override the "related" setting.

It appears to work great for me, but I don't have a lot of adoption scenarios in my tree so it would be good if you could see if this resolves some of the issues you've been seeing.

**Comment by hartenthaler** [comment]
Great, I will test it today.

**Comment by Neriderc** [comment]
Thanks! I trigger this scan any time the "mark non-related in different colour" option is set. As you know I originally planned to only run the check when there was an adoption record, but you pointed out partners as well. As it's pretty quick to run, I've opted not to do these checks at this point. Given the order things happen, it would get a bit more complicated and require new logic to scan the tree for non-relatives before generating the list of relatives. 

Currently we generate the list of relatives first, then generate our tree for display second. We'd have to generate the tree for display first, scan it for non-relatives, then if non-relatives were found we would then have to update our display tree or generate it a second time. 

I thought I'd leave that for now. You might have other ideas on a better approach?

**Comment by hartenthaler** [comment]
I found a fundamental problem, because the tree of persons in the diagram is incomplete in many cases (I'm using the "refactor_related" branch for the test).

1. Doing some code review, I found in line `1077` in `functions_dot.php` "`return false;`". I do not understand why this line is there.
2.  Are you sure that the stop person list is ignored when you generate the "full" tree for the starting persons?
3. In line `344` you are generating the "full" list. This list should contain for all starting persons the combined list of all biological ancestors and all of their biological descendants. I'm not sure if this "full" list is generated for all starting persons.
4. My development system found 45 warnings in `functions_dot.php`. For example in line `537` there is "@param char $gender (F/M/U)" but "char" is not defined. There are no type definitions in the definition lines of the functions, for example instead of
`function getGenderColour($gender, $related = TRUE)` it should be
`function getGenderColour(string $gender, bool $related = TRUE)`.
In many cases the definitions in the @param block do not correspond to the parameters of the functions.
5. From my point of view the functions are too complex. This is a result of the history of this module where so many programmers added something to the code. Refactoring would be necessary to understand the code.

**Comment by Neriderc** [comment]
> I found a fundamental problem, because the tree of persons in the diagram is incomplete in many cases (I'm using the "refactor_related" branch for the test).

The tree itself? That shouldn't have been changed, just the colours of the records.

>     1. Doing some code review, I found in line `1077` in `functions_dot.php` "`return false;`". I do not understand why this line is there.

This exits the function. From my understanding, this is the appropriate way to do this in PHP. The reason we exit the function is that the individual concerned has already been added. 

>     2. Are you sure that the stop person list is ignored when you generate the "full" tree for the starting persons?

Hmm no, good spotting. I'll fix this.

>     3. In line `344` you are generating the "full" list. This list should contain for all starting persons the combined list of all biological ancestors and all of their biological descendants. I'm not sure if this "full" list is generated for all starting persons.

It should work for all starting persons, and my testing has this working with multiple starting people.

>     4. My development system found 45 warnings in `functions_dot.php`. For example in line `537` there is "@param char $gender (F/M/U)" but "char" is not defined. There are no type definitions in the definition lines of the functions, for example instead of
>        `function getGenderColour($gender, $related = TRUE)` it should be
>        `function getGenderColour(string $gender, bool $related = TRUE)`.
>        In many cases the definitions in the @param block do not correspond to the parameters of the functions.

Yes, this is historical. Git Blame shows this section as dating from 2012.  I am trying to update things as I go, but haven't made any special effort to update functions that I haven't touched.

I'm also not super familiar with using the IDE in this scenario - a module for webtrees. I'm using PHPStorm and it shows many errors that are simply due to the function coming from webtrees, which the IDE is not aware of. This makes it difficult to identify errors that I need to pay attention to. Have you used PHPStorm? If so, do you know of a way to have it understand the context within the webtrees project so irrelevant errors are not shown?

>     5. From my point of view the functions are too complex. This is a result of the history of this module where so many programmers added something to the code. Refactoring would be necessary to understand the code.

While I agree, getting familiar with the code base is something that takes time, and I don't think I'm familiar enough to attempt this yet. It's likely to take quite some time as I really only have an hour or two here or there to work on things. However, I'll happily accept pull requests if you're offering :slightly_smiling_face:.

**Comment by Neriderc** [comment]
I got annoyed enough by the two extra seconds scanning the tree that I started looking at running the scan only when non-relatives were found. While doing this, I found further issues with colouring (which, funnily enough, wouldn't have happened if I was more familiar with the code base :)).

I've updated this branch to correct this issue and also to implement the scan for non-relatives before doing the full tree check.

> I found a fundamental problem, because the tree of persons in the diagram is incomplete in many cases (I'm using the "refactor_related" branch for the test).

It would be great to hear more about this, as I haven't seen any cases where persons were missing. Perhaps this new version fixes it anyway, as things happen in a different order.

**Comment by Neriderc** [comment]
I haven't come across more issues so will merge this. @hartenthaler when you get a chance it would be good to hear if you still have issues.

**Comment by hartenthaler** [comment]
Thank you! I will be back the day after tomorrow.

**Pull request merged**
