### PR TITLE
Settings updates - dropdown list and sharing function

### LINKED ISSUE #325: Add easy to access list of saved settings, option to share
We should add an optional new section at the top that has a dropdown list of saved settings.

This should be optional, enabled and disabled with a checkbox in the advanced settings in the File settings section, near where the settings are saved.

This should be disabled by default.

The intent is to add a way for an admin to create saved versions of settings for other users (via "Masquerade as user" in webtrees), then be able to present an easy to access list of settings that user can choose from.

Proposed mock-up:

image

Checklist:
- New section :white_check_mark: 
- Option to show or hide section :white_check_mark: 
- Disabled by default :white_check_mark: 
- Add to admin panel so default setting can be changed by admin :white_check_mark: 
- Load settings when settings ID in URL :white_check_mark: 
- Add ability to copy URL for these settings :white_check_mark: 
- Remove record of shared setting when saved setting record is deleted :white_check_mark: 
- Allow settings owner to un-share settings, removing record from shared settings preference :white_check_mark:

### PR DESCRIPTION
**Pull request by Neriderc**
Added option to enable a new section that allows choosing saved settings from a dropdown list. An admin could masquerade as a user, set up some settings in the advanced section, then enable this section for the user to easily pick between pre-prepared diagrams.

Also added option to share settings via a URL. The owner of settings can create a sharing link, then another user can load the settings via this link. If the settings are deleted by the original user, the link will no longer work.

Closes #325

### CODE REVIEW

**Comment by schuco** [comment]
> @schuco if you feel you want a separation of options based on user type, then we can still consider it. I think perhaps wait and see what this functionality comes out like,
Don't mind my comment, I thought this might have been easyer to implement.

**Comment by Neriderc** [comment]
It might be easy to implement, I'm not actually sure. I'm not entirely sure I understand what it is you were suggesting :slightly_frowning_face:.

Was it that only admins would be able to create links? Given a settings link is no different to downloading a settings file and sending it to someone (or simply telling them which settings to use), I'm not sure I understand the point. A settings link will not allow someone to see details on the tree they would not otherwise see. The name and details will just say "Private" if a person doesn't have permission to view a record. This is not a change from the current state.
image

**Comment by schuco** [comment]
Sorry for the confusion I brought in.
Don't mind my comment, I thought that restricting a function to admins might have been easyer to implement.

**Comment by Neriderc** [comment]
It probably wouldn't be too difficult. Let's leave it as is for now, and if you still feel you'd like this option after you've used it this way for a while then let me know and I'd be happy to have a closer look :slightly_smiling_face:

**Pull request merged**
